config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :new, :create, :show] do
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: {scope: :list_id}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
def new
  @list = List.find(params[:list_id])
 @bookmark = Bookmark.new
end

def create
  @list = List.find(params[:list_id])
  @bookmark = Bookmark.new(bookmark_params)
  @bookmark.list = @list
  @bookmark.save
end

private

def bookmark_params
  params.require(:bookmark).permit(:movie_id, :comment)

end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end

  end

  private

  def list_params
    params.required(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Choose a movie</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :movie_id, collection: Movie.all %>
<%= f.input :comment %>
<%= f.button :submit, class: 'btn btn-primary mt-4' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand" href="#">
      <img src="https://png.pngtree.com/png-clipart/20221006/original/pngtree-popcorn-logo-png-image_8661040.png" alt="Logo" width="30" height="24">
    </a>
    <%= link_to "New List", new_list_path, class: "btn btn-primary"  %>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Pages Index List</h1>


<%= link_to "New List", new_list_path, class: "btn btn-primary"  %>

<div class="container">
  <div class="d-flex">
    <% @lists.each do |list| %>
      <div class="card" style="width: 18rem;">
        <img src="https://static.vecteezy.com/system/resources/thumbnails/046/924/864/small/smoke-fog-steam-red-dark-podium-night-retro-brick-stage-garage-room-corridor-bar-empty-space-with-spot-lights-realistic-background-3d-rendering-illustration-high-quality-photo.jpg" class="card-img-top" alt="...">
        <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Create a movie list</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name, input_html: { class: 'form-control' } %>
  <%= f.button :submit, class: 'btn btn-primary mt-4' %>
<% end %>

app/views/lists/show.html.erb
<%= link_to "Back", lists_path %>

<%= link_to "Add a movie",  new_list_bookmark_path(@list) %>



<div class="container">
  <h2>My List</h2>

  <div class="d-flex">
    <% @list.movies.each do |movie| %>
      <div class="card" style="width: 18rem;">
          <img src="<%= movie.poster_url %>" class="card-img-top" alt="...">
          <div class="card-body">
              <h5 class="card-title"><%= movie.title %></h5>
              <p class="card-text"><%= movie.overview %></p>
              <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
      </div>
    <% end %>
  </div>
</div>